"""
hyper_network.py
================
Network AE — HyperNetwork

A model that generates the weights for the main 'TradeDecisionNet' based 
on the current market regime, providing ultimate adaptation.
"""
from __future__ import annotations
import torch
import torch.nn as nn

class HyperNet(nn.Module):
    def __init__(self, regime_dim: int, target_dim: int):
        super().__init__()
        # Takes regime embedding and produces a flattened vector of weights
        self.gen = nn.Sequential(
            nn.Linear(regime_dim, 64),
            nn.ReLU(),
            nn.Linear(64, target_dim)
        )

    def forward(self, regime_feat: torch.Tensor):
        return self.gen(regime_feat)

class MainNet(nn.Module):
    """Network that uses weights generated by the HyperNet."""
    def __init__(self, input_dim: int):
        super().__init__()
        self.input_dim = input_dim

    def forward(self, x, weights_flat):
        # weights_flat: (Batch, W)
        # Apply weights manually (Dynamic Linear layer)
        # x: (Batch, input_dim)
        # Assuming single layer for demo
        w = weights_flat.view(-1, 3, self.input_dim) # (Batch, Out, In)
        # b = weights_flat[:, -3:] # bias
        
        # Batch Matrix Multiply
        out = torch.bmm(w, x.unsqueeze(-1)).squeeze(-1)
        return out
