"""Professional technical and institutional trader skill catalog.

The catalog turns the user's complete skill maps into discoverable project data
so agents can inspect, search, and load skills by role. Only some skills are
executable; the rest are knowledge/process capabilities that still appear in
agent loadouts and documentation.
"""
from __future__ import annotations

from .core import SkillDefinition


def _d(prefix: str, key: str, name: str, category: str, components: list[str], tags: list[str], roles: list[str], desc: str = "") -> SkillDefinition:
    return SkillDefinition(
        id=f"{prefix}_{key}",
        name=name,
        category=category,
        description=desc or name,
        components=tuple(components),
        tags=tuple(tags),
        agent_roles=tuple(roles),
    )


TECHNICAL_TRADER_SKILLS: list[SkillDefinition] = [
    _d("ta", "foundational_markets", "Understanding Financial Markets", "TA 01 Foundational Knowledge", ["stocks", "forex", "commodities", "crypto", "derivatives"], ["market", "foundation"], ["all"]),
    _d("ta", "core_principles", "Core Principles of Technical Analysis", "TA 01 Foundational Knowledge", ["market discounts everything", "prices trend", "history repeats"], ["technical-analysis"], ["all"]),
    _d("ta", "math_statistics", "Mathematics and Statistics", "TA 01 Foundational Knowledge", ["percentages", "probability", "standard deviation", "regression", "risk/reward"], ["quant", "statistics"], ["research", "analyst", "risk_officer"]),
    _d("ta", "chart_types", "Chart Types Mastery", "TA 02 Chart Reading", ["line", "bar OHLC", "candlestick", "renko", "heikin ashi", "point and figure", "kagi", "volume profile"], ["charts"], ["analyst", "research"]),
    _d("ta", "timeframe_analysis", "Timeframe Analysis", "TA 02 Chart Reading", ["scalping", "day trading", "swing", "position", "multi-timeframe analysis"], ["mta", "trend"], ["analyst", "strategist", "coordinator"]),
    _d("ta", "candlestick_patterns", "Candlestick Pattern Recognition", "TA 02 Chart Reading", ["doji", "hammer", "shooting star", "engulfing", "harami", "morning star", "evening star", "three soldiers/crows"], ["candles", "pattern"], ["analyst", "strategist"]),
    _d("ta", "reversal_patterns", "Reversal Pattern Analysis", "TA 03 Chart Pattern Analysis", ["head and shoulders", "double top/bottom", "triple top/bottom", "rounding", "diamond", "V top/bottom"], ["pattern", "reversal"], ["analyst", "strategist"]),
    _d("ta", "continuation_patterns", "Continuation Pattern Analysis", "TA 03 Chart Pattern Analysis", ["flags", "pennants", "ascending triangle", "descending triangle", "rectangle", "cup and handle", "wedge"], ["pattern", "continuation"], ["analyst", "strategist"]),
    _d("ta", "bilateral_patterns", "Bilateral Pattern Analysis", "TA 03 Chart Pattern Analysis", ["symmetrical triangle", "broadening formation", "megaphone"], ["pattern", "breakout"], ["analyst", "strategist"]),
    _d("ta", "trend_indicators", "Trend Indicators", "TA 04 Technical Indicators", ["SMA", "EMA", "WMA", "MA ribbon", "MACD", "Parabolic SAR", "ADX", "Ichimoku", "Supertrend", "DEMA", "TEMA"], ["indicator", "trend"], ["analyst", "strategist"]),
    _d("ta", "momentum_indicators", "Momentum Indicators", "TA 04 Technical Indicators", ["RSI", "Stochastic", "CCI", "Williams %R", "ROC", "momentum", "Awesome Oscillator", "CMO"], ["indicator", "momentum"], ["analyst", "strategist"]),
    _d("ta", "volatility_indicators", "Volatility Indicators", "TA 04 Technical Indicators", ["Bollinger Bands", "ATR", "Keltner", "Donchian", "standard deviation", "VIX"], ["indicator", "volatility"], ["analyst", "risk_officer"]),
    _d("ta", "volume_indicators", "Volume Indicators", "TA 04 Technical Indicators", ["volume", "OBV", "VWAP", "accumulation/distribution", "CMF", "MFI", "volume profile", "Klinger"], ["indicator", "volume"], ["analyst", "strategist"]),
    _d("ta", "support_resistance", "Support and Resistance Tools", "TA 04 Technical Indicators", ["horizontal levels", "trendlines", "Fibonacci retracement", "Fibonacci extension", "pivot points", "MA S/R", "supply/demand"], ["levels", "support-resistance"], ["analyst", "strategist", "execution"]),
    _d("ta", "price_action", "Price Action Trading", "TA 05 Advanced Analysis", ["raw price", "market structure", "order flow", "naked charts", "BOS", "CHoCH"], ["price-action", "structure"], ["analyst", "strategist"]),
    _d("ta", "elliott_wave", "Elliott Wave Theory", "TA 05 Advanced Analysis", ["impulse waves", "corrective waves", "ABC", "degrees", "fractals", "wave rules"], ["wave", "advanced"], ["analyst", "research"]),
    _d("ta", "harmonic_patterns", "Harmonic Patterns", "TA 05 Advanced Analysis", ["Gartley", "Butterfly", "Bat", "Crab", "Shark", "Cypher", "ABCD"], ["harmonic", "pattern"], ["analyst", "strategist"]),
    _d("ta", "wyckoff_method", "Wyckoff Method", "TA 05 Advanced Analysis", ["accumulation", "distribution", "spring", "upthrust", "market cycle", "composite man"], ["wyckoff", "institutional"], ["analyst", "research"]),
    _d("ta", "smart_money_concepts", "Smart Money Concepts", "TA 05 Advanced Analysis", ["order blocks", "fair value gaps", "liquidity sweeps", "breaker blocks", "inducement", "premium/discount"], ["smc", "institutional"], ["analyst", "strategist"]),
    _d("ta", "divergence_analysis", "Divergence Analysis", "TA 05 Advanced Analysis", ["regular divergence", "hidden divergence", "RSI", "MACD", "Stochastic", "OBV"], ["divergence", "momentum"], ["analyst", "strategist"]),
    _d("ta", "intermarket_analysis", "Intermarket Analysis", "TA 05 Advanced Analysis", ["USD vs Gold", "Oil vs CAD", "bonds vs equities", "DXY vs commodities"], ["correlation", "macro"], ["analyst", "sentiment", "portfolio"]),
    _d("ta", "charting_platforms", "Charting Software Proficiency", "TA 06 Platform and Tools", ["TradingView", "MT4", "MT5", "Thinkorswim", "NinjaTrader", "Bloomberg", "TrendSpider", "TC2000"], ["platform"], ["execution", "analyst"]),
    _d("ta", "screeners_scanners", "Screener and Scanner Skills", "TA 06 Platform and Tools", ["technical filters", "alerts", "breakouts", "indicator signals", "real-time scanning"], ["scanner", "alerts"], ["monitoring", "research"]),
    _d("ta", "programming_automation", "Programming and Automation", "TA 06 Platform and Tools", ["Pine Script", "MQL4", "MQL5", "Python", "R", "bots", "algorithms"], ["automation", "coding"], ["research", "optimization", "execution"]),
    _d("ta", "backtesting_forward_testing", "Backtesting and Forward Testing", "TA 06 Platform and Tools", ["historical testing", "walk-forward", "paper trading", "demo account", "outcomes"], ["backtest", "validation"], ["research", "simulation", "optimization"]),
    _d("ta", "position_sizing", "Position Sizing", "TA 07 Risk Management", ["fixed dollar risk", "percentage risk", "1-2% rule", "Kelly Criterion", "hedging"], ["risk", "sizing"], ["risk_officer", "strategist", "portfolio"]),
    _d("ta", "stop_loss", "Stop-Loss Strategies", "TA 07 Risk Management", ["fixed stop", "ATR stop", "trailing stop", "Parabolic SAR stop", "structure stop", "time stop"], ["risk", "stop"], ["risk_officer", "execution"]),
    _d("ta", "risk_reward", "Risk/Reward Ratio", "TA 07 Risk Management", ["R:R before entry", "1:2", "1:3", "win rate trade-off", "expectancy"], ["risk", "rrr"], ["risk_officer", "strategist"]),
    _d("ta", "portfolio_money_management", "Portfolio and Money Management", "TA 07 Risk Management", ["diversification", "correlation", "drawdown", "scaling", "hedging"], ["portfolio", "risk"], ["portfolio", "risk_officer"]),
    _d("ta", "emotional_control", "Emotional Control", "TA 08 Trading Psychology", ["fear", "greed", "FOMO", "revenge trading", "overconfidence"], ["psychology"], ["all"]),
    _d("ta", "discipline_consistency", "Discipline and Consistency", "TA 08 Trading Psychology", ["plan adherence", "drawdown discipline", "consistent execution"], ["psychology", "process"], ["all"]),
    _d("ta", "self_awareness_journaling", "Self-Awareness and Journaling", "TA 08 Trading Psychology", ["trade journal", "emotions", "performance reviews", "accountability"], ["journal", "psychology"], ["monitoring", "optimization", "all"]),
    _d("ta", "mindfulness_resilience", "Mindfulness and Mental Resilience", "TA 08 Trading Psychology", ["meditation", "breathing", "visualization", "accepting losses"], ["psychology"], ["all"]),
    _d("ta", "bias_awareness", "Cognitive Bias Awareness", "TA 08 Trading Psychology", ["confirmation", "anchoring", "recency", "loss aversion", "sunk cost", "overconfidence"], ["bias", "psychology"], ["all"]),
    _d("ta", "trading_plan", "Trading Plan Development", "TA 09 Trade Planning and Execution", ["market", "entry criteria", "exit criteria", "risk parameters", "time rules"], ["plan", "execution"], ["strategist", "execution", "coordinator"]),
    _d("ta", "trade_entry", "Trade Entry Skills", "TA 09 Trade Planning and Execution", ["breakout", "pullback", "reversal", "confirmation", "limit vs market"], ["entry", "execution"], ["strategist", "execution"]),
    _d("ta", "trade_management", "Trade Management Skills", "TA 09 Trade Planning and Execution", ["breakeven", "partial profits", "pyramiding", "multi-timeframe management", "re-entry"], ["management", "execution"], ["execution", "strategist"]),
    _d("ta", "trade_exit", "Trade Exit Skills", "TA 09 Trade Planning and Execution", ["profit targets", "trailing stops", "invalidation", "time exits"], ["exit", "execution"], ["execution", "risk_officer"]),
    _d("ta", "analytical_thinking", "Analytical Thinking", "TA 10 Analytical and Soft Skills", ["pattern recognition", "logical reasoning", "trend interpretation"], ["soft-skill"], ["all"]),
    _d("ta", "focus_concentration", "Focus and Concentration", "TA 10 Analytical and Soft Skills", ["screen time", "chart study", "avoid distractions", "peak performance"], ["soft-skill"], ["all"]),
    _d("ta", "patience", "Patience", "TA 10 Analytical and Soft Skills", ["wait for setups", "avoid forcing", "let winners run"], ["soft-skill"], ["all"]),
    _d("ta", "adaptability", "Adaptability", "TA 10 Analytical and Soft Skills", ["market conditions", "new instruments", "evolving methods"], ["soft-skill", "regime"], ["all"]),
    _d("ta", "recordkeeping_metrics", "Record-Keeping and Performance Metrics", "TA 10 Analytical and Soft Skills", ["win rate", "average win/loss", "profit factor", "drawdown", "Sharpe", "expectancy"], ["metrics", "journal"], ["monitoring", "optimization"]),
    _d("ta", "continuous_learning", "Continuous Learning", "TA 10 Analytical and Soft Skills", ["books", "courses", "market replays", "mentors", "communities"], ["learning"], ["all"]),
    _d("ta", "market_structure_analysis", "Market Structure Analysis", "TA 11 Specialized Skills", ["HH/HL", "LH/LL", "ranges", "regime changes"], ["structure", "specialized"], ["analyst", "regime", "strategist"]),
    _d("ta", "sector_rotation", "Sector and Market Rotation Analysis", "TA 11 Specialized Skills", ["sector relative strength", "risk-on/off", "leaders", "laggards"], ["sector", "portfolio"], ["portfolio", "research"]),
    _d("ta", "seasonal_cycles", "Seasonal and Cyclical Analysis", "TA 11 Specialized Skills", ["commodity seasonality", "election cycles", "earnings", "calendar effects"], ["seasonality", "cycle"], ["research"]),
    _d("ta", "sentiment_analysis", "Sentiment Analysis", "TA 11 Specialized Skills", ["put/call", "fear and greed", "COT", "breadth", "McClellan"], ["sentiment"], ["sentiment", "analyst"]),
    _d("ta", "order_flow_level2", "Order Flow and Level 2 Analysis", "TA 11 Specialized Skills", ["order book", "time and sales", "bid/ask", "institutional activity"], ["order-flow", "execution"], ["execution", "analyst"]),
    _d("ta", "gap_analysis", "Gap Analysis", "TA 11 Specialized Skills", ["common gaps", "breakaway", "runaway", "exhaustion", "gap fill"], ["gap", "price-action"], ["analyst", "strategist"]),
]

INSTITUTIONAL_TRADER_SKILLS: list[SkillDefinition] = [
    _d("inst", "academic_knowledge", "Academic Knowledge", "INST 01 Foundational/Educational", ["finance", "economics", "mathematics", "business", "accounting"], ["education"], ["all"]),
    _d("inst", "certifications", "Professional Certifications", "INST 01 Foundational/Educational", ["CFA", "FRM", "FINRA Series 7", "Series 63/66"], ["certification", "compliance"], ["all"]),
    _d("inst", "quantitative_ability", "Numeracy and Quantitative Ability", "INST 01 Foundational/Educational", ["arithmetic", "statistics", "algorithmic methods", "probability"], ["quant"], ["research", "risk_officer"]),
    _d("inst", "chart_pattern_recognition", "Chart Reading and Pattern Recognition", "INST 02 Technical Analysis", ["head and shoulders", "triangles", "candlesticks", "flags", "rectangles"], ["pattern"], ["analyst", "strategist"]),
    _d("inst", "trend_analysis", "Trend Analysis", "INST 02 Technical Analysis", ["trendlines", "trend phases", "HH/HL", "LH/LL", "multi-timeframe"], ["trend"], ["analyst", "regime"]),
    _d("inst", "support_resistance", "Support and Resistance Analysis", "INST 02 Technical Analysis", ["horizontal", "dynamic", "psychological", "Fibonacci", "pivot"], ["levels"], ["analyst", "execution"]),
    _d("inst", "market_structure", "Market Structure Analysis", "INST 02 Technical Analysis", ["BOS", "CHoCH", "swing highs/lows", "HTF/LTF alignment", "ranges"], ["structure"], ["analyst", "regime", "strategist"]),
    _d("inst", "moving_averages", "Moving Averages", "INST 03 Indicator Mastery", ["EMA", "SMA", "50-day", "100-day", "200-day", "crossovers", "dynamic S/R"], ["indicator", "trend"], ["analyst"]),
    _d("inst", "vwap", "VWAP", "INST 03 Indicator Mastery", ["session VWAP", "anchored VWAP", "rolling VWAP", "deviation bands", "multi-session VWAP"], ["vwap", "institutional"], ["analyst", "execution"]),
    _d("inst", "rsi", "RSI", "INST 03 Indicator Mastery", ["overbought", "oversold", "divergence", "volume confirmation"], ["indicator", "momentum"], ["analyst"]),
    _d("inst", "macd", "MACD", "INST 03 Indicator Mastery", ["MACD line", "signal line", "histogram", "bullish crossover", "bearish crossover"], ["indicator", "trend"], ["analyst"]),
    _d("inst", "atr", "Average True Range", "INST 03 Indicator Mastery", ["volatility", "position sizing", "stop placement"], ["indicator", "risk"], ["risk_officer", "analyst"]),
    _d("inst", "bollinger_bands", "Bollinger Bands", "INST 03 Indicator Mastery", ["volatility", "mean reversion", "squeeze", "band walking"], ["indicator", "volatility"], ["analyst"]),
    _d("inst", "stochastic", "Stochastic Oscillator", "INST 03 Indicator Mastery", ["overbought", "oversold", "divergence", "%K/%D", "MTF alignment"], ["indicator", "momentum"], ["analyst"]),
    _d("inst", "ichimoku", "Ichimoku Cloud", "INST 03 Indicator Mastery", ["Tenkan", "Kijun", "Kumo", "Chikou", "future cloud"], ["indicator", "trend"], ["analyst"]),
    _d("inst", "fibonacci_tools", "Fibonacci Tools", "INST 03 Indicator Mastery", ["retracement", "extensions", "time zones", "fan", "arcs", "confluence"], ["fibonacci", "levels"], ["analyst", "strategist"]),
    _d("inst", "momentum_indicators", "Momentum Indicators", "INST 03 Indicator Mastery", ["ROC", "CCI", "Williams %R", "ADX"], ["indicator", "momentum"], ["analyst"]),
    _d("inst", "volume_profile", "Volume Profile Analysis", "INST 04 Volume Analysis", ["POC", "VAH", "VAL", "HVN", "LVN", "P-shape", "b-shape", "D-shape"], ["volume-profile", "institutional"], ["analyst", "execution"]),
    _d("inst", "volume_analysis", "Volume Analysis", "INST 04 Volume Analysis", ["volume spikes", "climax", "dry-ups", "OBV", "A/D", "CMF"], ["volume"], ["analyst", "strategist"]),
    _d("inst", "order_flow", "Order Flow Analysis", "INST 04 Volume Analysis", ["tape reading", "Level 2", "footprint", "delta", "cumulative delta", "bid/ask imbalance", "icebergs"], ["order-flow", "institutional"], ["execution", "analyst"]),
    _d("inst", "smart_money", "Smart Money Concepts", "INST 05 SMC/Institutional", ["order blocks", "breaker blocks", "mitigation blocks", "FVG", "liquidity voids", "premium/discount"], ["smc", "institutional"], ["analyst", "strategist"]),
    _d("inst", "liquidity_concepts", "Liquidity Concepts", "INST 05 SMC/Institutional", ["buy-side liquidity", "sell-side liquidity", "stop hunts", "liquidity pools", "inducement"], ["liquidity", "institutional"], ["analyst", "execution"]),
    _d("inst", "institutional_footprint", "Institutional Footprint Detection", "INST 05 SMC/Institutional", ["Wyckoff", "spring", "upthrust", "composite man", "institutional candles"], ["footprint", "institutional"], ["analyst", "research"]),
    _d("inst", "macroeconomic_analysis", "Macroeconomic Analysis", "INST 06 Fundamental Analysis", ["GDP", "interest rates", "inflation", "employment", "central banks", "yield curve", "currency correlations"], ["macro", "fundamental"], ["sentiment", "research"]),
    _d("inst", "equity_fundamentals", "Company/Equity Fundamental Analysis", "INST 06 Fundamental Analysis", ["earnings", "balance sheet", "income statement", "cash flow", "valuation", "DCF", "sector rotation"], ["fundamental", "equity"], ["research", "portfolio"]),
    _d("inst", "sentiment_analysis", "Sentiment Analysis", "INST 06 Fundamental Analysis", ["COT", "put/call", "VIX", "breadth", "retail sentiment", "news", "social media"], ["sentiment"], ["sentiment", "research"]),
    _d("inst", "inter_market_analysis", "Inter-Market Analysis", "INST 06 Fundamental Analysis", ["bond/equity", "currency/commodity", "DXY", "Gold", "Oil", "sector rotation", "risk-on/off"], ["correlation", "macro"], ["sentiment", "portfolio"]),
    _d("inst", "position_sizing", "Position Sizing", "INST 07 Risk Management", ["fixed fractional", "Kelly", "volatility adjusted", "portfolio heat", "correlation adjusted"], ["risk", "sizing"], ["risk_officer", "portfolio"]),
    _d("inst", "risk_reward", "Risk/Reward Assessment", "INST 07 Risk Management", ["minimum R:R", "expected value", "win rate optimization", "breakeven"], ["risk", "rrr"], ["risk_officer", "strategist"]),
    _d("inst", "stop_loss", "Stop-Loss Management", "INST 07 Risk Management", ["fixed", "ATR trailing", "structure", "time", "volatility", "mental vs hard"], ["risk", "stop"], ["risk_officer", "execution"]),
    _d("inst", "portfolio_risk", "Portfolio Risk Management", "INST 07 Risk Management", ["diversification", "correlation", "drawdown", "VaR", "stress testing", "hedging"], ["portfolio", "risk"], ["risk_officer", "portfolio"]),
    _d("inst", "professional_platforms", "Professional Trading Platforms", "INST 08 Platforms and Tools", ["Bloomberg", "Eikon", "TradingView", "MT4/5", "CQG", "TOS", "Sterling", "Bookmap", "Sierra", "NinjaTrader"], ["platform"], ["execution", "analyst"]),
    _d("inst", "execution_tools", "Execution Tools", "INST 08 Platforms and Tools", ["DMA", "ECN", "Dark Pools", "TWAP", "VWAP", "Iceberg", "SOR", "FIX"], ["execution", "microstructure"], ["execution"]),
    _d("inst", "screening_scanning", "Screening and Scanning Tools", "INST 08 Platforms and Tools", ["screeners", "options scanners", "heat maps", "relative strength", "pre-market", "news feeds"], ["scanner"], ["monitoring", "research"]),
    _d("inst", "quant_programming", "Quantitative and Programming Tools", "INST 08 Platforms and Tools", ["Python", "R", "SQL", "MATLAB", "Excel/VBA", "API integration"], ["coding", "quant"], ["research", "optimization", "execution"]),
    _d("inst", "chart_types", "Chart Types Mastery", "INST 09 Charts and Timeframes", ["candlestick", "bar", "line", "renko", "heikin ashi", "point and figure", "tick", "range", "footprint", "market profile"], ["charts"], ["analyst"]),
    _d("inst", "multi_timeframe", "Multi-Timeframe Analysis", "INST 09 Charts and Timeframes", ["monthly", "weekly", "daily", "4H", "1H", "15M", "5M", "1M", "top-down", "alignment"], ["mta"], ["analyst", "strategist"]),
    _d("inst", "order_types", "Order Types Mastery", "INST 10 Order Types and Execution", ["market", "limit", "stop", "stop-limit", "trailing stop", "OCO", "bracket", "iceberg", "FOK", "GTC", "IOC"], ["execution", "orders"], ["execution", "risk_officer"]),
    _d("inst", "execution_quality", "Execution Quality Skills", "INST 10 Order Types and Execution", ["slippage", "spread", "order timing", "front-running avoidance", "microstructure", "liquidity windows"], ["execution", "quality"], ["execution", "broker"]),
    _d("inst", "strategy_types", "Strategy Types", "INST 11 Trading Strategies", ["scalping", "day trading", "swing", "position", "algorithmic", "arbitrage", "pairs", "mean reversion", "momentum", "event-driven", "stat arb"], ["strategy"], ["strategist", "research"]),
    _d("inst", "backtesting_strategy", "Backtesting and Strategy Development", "INST 11 Trading Strategies", ["historical", "walk-forward", "Monte Carlo", "optimization", "out-of-sample", "paper trading", "Sharpe", "Sortino", "drawdown", "profit factor"], ["backtest", "validation"], ["research", "simulation", "optimization"]),
    _d("inst", "emotional_discipline", "Emotional Discipline", "INST 12 Psychological/Soft Skills", ["fear", "greed", "revenge", "patience", "consistency", "drawdowns"], ["psychology"], ["all"]),
    _d("inst", "decision_pressure", "Decision-Making Under Pressure", "INST 12 Psychological/Soft Skills", ["fast decisions", "stress management", "large trades", "risk minimization"], ["psychology", "execution"], ["execution", "coordinator"]),
    _d("inst", "communication", "Communication and Interpersonal Skills", "INST 12 Psychological/Soft Skills", ["portfolio managers", "analysts", "traders", "written communication", "influence"], ["communication"], ["coordinator", "all"]),
    _d("inst", "cognitive_skills", "Cognitive Skills", "INST 12 Psychological/Soft Skills", ["analytical", "critical", "probabilistic", "adaptive", "bias awareness"], ["cognitive"], ["all"]),
    _d("inst", "journaling_review", "Journaling and Self-Review", "INST 12 Psychological/Soft Skills", ["journal", "daily review", "weekly review", "mistakes", "win rate", "average R", "expectancy"], ["journal", "metrics"], ["monitoring", "optimization"]),
    _d("inst", "regulatory_knowledge", "Regulatory Knowledge", "INST 13 Regulatory and Compliance", ["SEC", "FINRA", "MiFID II", "FCA", "exchange rules", "insider trading", "KYC", "AML", "best execution", "reporting"], ["compliance", "regulatory"], ["broker", "execution", "risk_officer"]),
    _d("inst", "ethics", "Ethics and Professional Conduct", "INST 13 Regulatory and Compliance", ["fiduciary", "conflicts", "Chinese Wall", "personal trading", "code of ethics"], ["ethics", "compliance"], ["all"]),
    _d("inst", "multi_asset", "Multi-Asset Class Proficiency", "INST 14 Asset Class Knowledge", ["equities", "fixed income", "FX", "commodities", "derivatives", "crypto", "structured products"], ["asset-class"], ["portfolio", "research", "broker"]),
    _d("inst", "options", "Options-Specific Skills", "INST 14 Asset Class Knowledge", ["Greeks", "Black-Scholes", "binomial", "vol surface", "spreads", "straddles", "iron condors", "implied vs historical vol"], ["options", "derivatives"], ["research", "risk_officer"]),
    _d("inst", "data_bigdata", "Data Analysis and Big Data", "INST 15 Technology and Infrastructure", ["real-time data", "alternative data", "machine learning", "NLP"], ["data", "ml"], ["research", "data_integration", "optimization"]),
    _d("inst", "network_infrastructure", "Network and Infrastructure", "INST 15 Technology and Infrastructure", ["low latency", "co-location", "redundancy", "failover", "multi-screen setup"], ["infrastructure", "execution"], ["execution", "broker"]),
    _d("inst", "daily_market_prep", "Daily Market Preparation", "INST 16 Market Awareness/Learning", ["pre-market", "calendar", "overnight sessions", "key levels", "news catalysts"], ["prep", "process"], ["coordinator", "analyst", "sentiment"]),
    _d("inst", "continuous_education", "Continuous Education", "INST 16 Market Awareness/Learning", ["research reports", "whitepapers", "conferences", "mentors", "market regimes", "market history"], ["learning"], ["all"]),
]

ALL_SKILL_DEFINITIONS = TECHNICAL_TRADER_SKILLS + INSTITUTIONAL_TRADER_SKILLS
